// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD43tttY-4A0D70IxDXfbowBAIvD1BMPL0',
    appId: '1:790077578955:web:d86f9118011ced449a054e',
    messagingSenderId: '790077578955',
    projectId: 'capstone-sss',
    authDomain: 'capstone-sss.firebaseapp.com',
    storageBucket: 'capstone-sss.appspot.com',
    measurementId: 'G-29SC1Q3G1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD57i6x84onru-CEIf3t0aXSrdbnPD0lLs',
    appId: '1:790077578955:android:5cabaaf51320e30b9a054e',
    messagingSenderId: '790077578955',
    projectId: 'capstone-sss',
    storageBucket: 'capstone-sss.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3iGDYPBOqR2TsveU8gdC6Wb4MYKgN9to',
    appId: '1:790077578955:ios:0c7160a0fe05b1209a054e',
    messagingSenderId: '790077578955',
    projectId: 'capstone-sss',
    storageBucket: 'capstone-sss.appspot.com',
    iosBundleId: 'com.example.studentSupportSystem',
  );
}
